{{ if .Values.hpa.create }}
apiVersion: {{ .Values.hpa.apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- with .Values.hpa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helm-chart.fullname" . }}
{{- with .Values.hpa.spec }}
  {{- toYaml . | nindent 2 }}
{{- end }}
behavior:
{{- with .Values.hpa.behavior }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{ end }}
