{{- if .Values.ingress.create -}}
{{- $fullName := include "helm-chart.fullname" . -}}
{{- $svcName := include "helm-chart.servicename" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    {{ if .Values.redirectToMaster }}
    redirectToMaster: 'true'
    {{ end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }} 
        {{- end }}
  {{- end }}
{{- end }}
