{{- if .Values.ingress.create -}}
{{- $fullName := include "helm-chart.fullname" . -}}
{{- $svcName := include "helm-chart.servicename" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    {{ if .Values.redirectToMaster }}
    redirectToMaster: 'true'
    {{ end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $svcName }}
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
