{{ if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}
type: Opaque
stringData:
{{- range $name, $val := .Values.secrets }}
  {{ $name }}: {{ $val | quote }}
{{- end }}
{{ end }}
