{{ if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.servicename" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  {{ if .Values.redirectToMaster }}
  type: ExternalName
  externalName: {{ include "helm-chart.fullname" . }}.myalbum.svc.cluster.local
  {{ else }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
  {{ end }}
{{ end }}
